import { createApp } from 'vue'
import App from './App.vue'
import './style.css'
import './quick-add.css'
import './remote-engine.css'
import './workspaces.css'
import './generation-settings.css'
import './editor-justify.css'
import './bulk-import.css'
import './bulk-export.js'
import './tencent-maas.css'
import './tencent-maas.js'
import './terminology-simple.css'
import './terminology-simple.js'

createApp(App).mount('#app')
